name: Continuous Build

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build-test:
        runs-on: windows-latest

        env:
            DOTNET_MULTILEVEL_LOOKUP: 1

        strategy:
            fail-fast: false
            matrix:
                version: [net6.0, netcoreapp3.1]

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '6.0.x'

        - uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '3.1.x'

        - name: Install dependencies
          run: dotnet restore SSMDataProtectionProvider.sln

        - name: Build solution
          run: dotnet build SSMDataProtectionProvider.sln --configuration Release --no-restore

        - name: Run tests
          run: >-
            dotnet test SSMDataProtectionProvider.sln --framework ${{matrix.version}} --no-build
            --logger "console;verbosity=detailed"